; MUI Welcome page
LangString MUI_TEXT_WELCOME_INFO_TITLE ${LANG_RUSSIAN} "Добро пожаловать в установщик ${PRODUCTNAME}!"
LangString MUI_TEXT_WELCOME_INFO_TEXT ${LANG_RUSSIAN} "Этот мастер установит ${PRODUCTNAME} — приложение для создания и прохождения проверочных работ.$\r$\n$\r$\nИдеально подходит для учителей, репетиторов и учеников.$\r$\n$\r$\nПеред продолжением закройте все остальные приложения."

; MUI Finish page
LangString MUI_TEXT_FINISH_INFO_TITLE ${LANG_RUSSIAN} "Завершение установки ${PRODUCTNAME}"
LangString MUI_TEXT_FINISH_INFO_TEXT ${LANG_RUSSIAN} "Установка ${PRODUCTNAME} успешно завершена!$\r$\n$\r$\nПрограмма готова к использованию.$\r$\nЯрлык для запуска вы найдёте на рабочем столе и в меню «Пуск».$\r$\n$\r$\nСпасибо, что выбрали наше приложение!$\r$\nПрисоединяйтесь к сообществу, чтобы предлагать идеи, сообщать об ошибках$\r$\nи получать новости об обновлениях:$\r$\n👉 https://vk.com/club240219050"
LangString MUI_TEXT_FINISH_RUN ${LANG_RUSSIAN} "Запустить ${PRODUCTNAME} сейчас"

; Tauri custom strings
LangString addOrReinstall ${LANG_RUSSIAN} "Переустановить / Восстановить"
LangString alreadyInstalled ${LANG_RUSSIAN} "Уже установлено"
LangString alreadyInstalledLong ${LANG_RUSSIAN} "${PRODUCTNAME} ${VERSION} уже установлен. Выберите действие и нажмите «Далее»."
LangString appRunning ${LANG_RUSSIAN} "${PRODUCTNAME} запущен! Пожалуйста, закройте его и попробуйте снова."
LangString appRunningOkKill ${LANG_RUSSIAN} "${PRODUCTNAME} запущен!$\nНажмите OK, чтобы завершить процесс."
LangString chooseMaintenanceOption ${LANG_RUSSIAN} "Выберите действие"
LangString choowHowToInstall ${LANG_RUSSIAN} "Выберите способ установки"
LangString createDesktop ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"
LangString dontUninstall ${LANG_RUSSIAN} "Не удалять"
LangString dontUninstallDowngrade ${LANG_RUSSIAN} "Не удалять (для этой версии откат без удаления отключён)"
LangString failedToKillApp ${LANG_RUSSIAN} "Не удалось завершить ${PRODUCTNAME}. Закройте его вручную и попробуйте снова."
LangString installingWebview2 ${LANG_RUSSIAN} "Установка WebView2..."
LangString newerVersionInstalled ${LANG_RUSSIAN} "Более новая версия ${PRODUCTNAME} уже установлена! Установка старой версии не рекомендуется. Если вы всё же хотите установить эту версию, сначала удалите текущую."
LangString older ${LANG_RUSSIAN} "старее"
LangString olderOrUnknownVersionInstalled ${LANG_RUSSIAN} "На вашей системе установлена $R4 версия ${PRODUCTNAME}. Рекомендуется удалить текущую версию перед установкой."
LangString silentDowngrades ${LANG_RUSSIAN} "Откат отключён для этого установщика. Используйте графический интерфейс для установки.$\n"
LangString unableToUninstall ${LANG_RUSSIAN} "Не удалось удалить!"
LangString uninstallApp ${LANG_RUSSIAN} "Удалить ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_RUSSIAN} "Удалить перед установкой"
LangString unknown ${LANG_RUSSIAN} "неизвестно"
LangString webview2AbortError ${LANG_RUSSIAN} "Не удалось установить WebView2! Приложение не может работать без него. Перезапустите установщик."
LangString webview2DownloadError ${LANG_RUSSIAN} "Ошибка: не удалось скачать WebView2 — $0"
LangString webview2DownloadSuccess ${LANG_RUSSIAN} "WebView2 успешно загружен"
LangString webview2Downloading ${LANG_RUSSIAN} "Скачивание WebView2..."
LangString webview2InstallError ${LANG_RUSSIAN} "Ошибка: установка WebView2 завершилась с кодом $1"
LangString webview2InstallSuccess ${LANG_RUSSIAN} "WebView2 успешно установлен"
LangString deleteAppData ${LANG_RUSSIAN} "Удалить данные приложения"
